name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++, clang++]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++ clang valgrind
      - name: Build and test
        env:
          CXX: ${{ matrix.compiler }}
        run: |
          make clean
          make test

  valgrind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++ valgrind
      - name: Run tests under valgrind
        env:
          PRERUN: "valgrind --error-exitcode=1 --leak-check=full"
        run: |
          make clean
          make test
